Fix deprecation errors in php-7.4.0
Curly braces for array or string access are deprecated and cause the
following error:
```
ErrorException: Array and string offset access syntax with curly braces is deprecated
```

Signed-off-by: Vitalii Rybalko <vilko.a@gmail.com>